apiVersion: v1
kind: Service
metadata:
  name: devopsdemo-service
  namespace: stag
spec:
  selector:
    app: devopsdemo-service
  ports:
    - port: 3000
      targetPort: 3000
      name: devopsdemo-service
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsdemo-service
  namespace: stag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsdemo-service
  template:
    metadata:
      labels:
        app: devopsdemo-service
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: devopsdemo-service
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          env:
            - name: KAFKA_PREFIX
              value: stag
            - name: KAFKA_HOST
              value: kafka.kafka
            - name: KAFKA_PORT
              value: "9094"
          envFrom:
            - secretRef:
                name: devopsdemo-stag
                optional: false
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devopsdemo-ingress
  namespace: stag
spec:
  rules:
    - host: testing.116.203.237.159.xip.io
      http:
        paths:
          - backend:
              serviceName: devopsdemo-service
              servicePort: 3000
            path: /api/university
  tls:
    - hosts:
        - testing.116.203.237.159.xip.io
